<?php

/**
 * Texte des Kundenportals in Deutsch und Englisch. Die Sprache kommt aus
 * ?sprache=, der Sitzung oder dem Konto; t('schluessel') liefert den Text.
 */

declare(strict_types=1);

function sprache(): string
{
    static $sprache = null;
    if ($sprache !== null) {
        return $sprache;
    }
    $wunsch = $_GET['sprache'] ?? $_POST['sprache'] ?? null;
    if ($wunsch === 'de' || $wunsch === 'en') {
        $_SESSION['sprache'] = $wunsch;
    }
    $sprache = $_SESSION['sprache'] ?? null;
    if ($sprache === null && function_exists('kundeAktuell')) {
        $k = kundeAktuell();
        $sprache = $k['sprache'] ?? null;
    }
    $sprache = $sprache === 'en' ? 'en' : 'de';

    return $sprache;
}

function t(string $schluessel, mixed ...$argumente): string
{
    $text = texte()[sprache()][$schluessel] ?? texte()['de'][$schluessel] ?? $schluessel;

    return $argumente === [] ? $text : vsprintf($text, $argumente);
}

function texte(): array
{
    static $t = null;
    if ($t !== null) {
        return $t;
    }
    $t = [
        'de' => [
            'portal' => 'Kundenportal',
            'anmelden' => 'Anmelden',
            'abmelden' => 'Abmelden',
            'zur_seite' => 'Zur Startseite',
            'sprache_wechseln' => 'English',
            'nav.uebersicht' => 'Übersicht',
            'nav.bestellungen' => 'Bestellungen',
            'nav.sendungen' => 'Sendungen',
            'nav.neu' => 'Neue Sendung',
            'nav.preise' => 'Preise',
            'nav.rechnungen' => 'Rechnungen',
            'nav.benutzer' => 'Benutzer',
            'nav.firma' => 'Firma',
            'nav.einstellungen' => 'Einstellungen',
            'login.titel' => 'Anmelden',
            'login.text' => 'Mit Passwort — oder ohne: wir schicken dir einen Anmeldelink per E-Mail.',
            'login.email' => 'E-Mail',
            'login.passwort' => 'Passwort',
            'login.knopf' => 'Anmelden',
            'login.link' => 'Anmeldelink per E-Mail schicken',
            'login.oder' => 'oder',
            'login.fehler' => 'E-Mail oder Passwort falsch — oder das Konto ist vorübergehend gesperrt.',
            'login.kein_passwort' => 'Für dieses Konto ist noch kein Passwort gesetzt. Nutze den Anmeldelink per E-Mail und setze danach ein Passwort.',
            'login.vergessen' => 'Passwort vergessen?',
            'login.registrieren' => 'Noch kein Konto? Jetzt registrieren',
            'login.abgelaufen' => 'Der Link ist ungültig oder abgelaufen. Bitte einen neuen anfordern.',
            'link.titel' => 'Schau in dein Postfach',
            'link.text' => 'Wenn zu %s ein Konto gehört, ist gerade eine E-Mail mit einem Link unterwegs. Der Link gilt %d Minuten und funktioniert einmal.',
            'link.zurueck' => 'Zurück zur Anmeldung',
            'registrieren.titel' => 'Konto anlegen',
            'registrieren.text' => 'Für Privatkunden: Bestellungen im Blick, Absenderadresse gespeichert. Wir bestätigen deine E-Mail-Adresse per Link — alle Bestellungen mit dieser Adresse landen dann in deinem Konto.',
            'registrieren.name' => 'Name',
            'registrieren.knopf' => 'Bestätigungslink schicken',
            'registrieren.business' => 'Geschäftskunde? Firmenkonten schaltet unser Team frei — <a href="%s">Konto anfragen</a>.',
            'vergessen.titel' => 'Passwort vergessen',
            'vergessen.text' => 'Wir schicken dir einen Link, mit dem du ein neues Passwort setzt.',
            'vergessen.knopf' => 'Link schicken',
            'passwort.titel' => 'Passwort setzen',
            'passwort.text_neu' => 'Optional: Mit einem Passwort meldest du dich künftig ohne E-Mail-Link an. Mindestens %d Zeichen.',
            'passwort.text' => 'Mindestens %d Zeichen.',
            'passwort.alt' => 'Bisheriges Passwort',
            'passwort.neu' => 'Neues Passwort',
            'passwort.wiederholung' => 'Neues Passwort wiederholen',
            'passwort.knopf' => 'Passwort speichern',
            'passwort.spaeter' => 'Später, weiter zur Übersicht',
            'passwort.alt_falsch' => 'Das bisherige Passwort stimmt nicht.',
            'passwort.ungleich' => 'Die Wiederholung stimmt nicht überein.',
            'passwort.gespeichert' => 'Passwort gespeichert.',
            'willkommen' => 'Willkommen, %s.',
            'willkommen.bestaetigt' => 'Deine E-Mail-Adresse ist bestätigt. %d Bestellungen wurden deinem Konto zugeordnet.',
            'uebersicht.privat.text' => 'Hier findest du alle Bestellungen, die du mit %s bezahlt hast.',
            'uebersicht.letzte' => 'Letzte Bestellungen',
            'uebersicht.alle' => 'Alle anzeigen',
            'uebersicht.keine' => 'Noch keine Bestellungen. Verschick dein erstes Paket über die Startseite.',
            'uebersicht.paket' => 'Paket verschicken',
            'uebersicht.absender' => 'Deine Absenderadresse',
            'uebersicht.absender.text' => 'Wird beim nächsten Paket vorbelegt.',
            'uebersicht.absender.fehlt' => 'Noch keine gespeichert — unter Einstellungen eintragen.',
            'uebersicht.monat' => 'Sendungen diesen Monat',
            'uebersicht.kosten' => 'Kosten netto diesen Monat',
            'uebersicht.offen' => 'Offene Rechnungen',
            'uebersicht.business.text' => 'Firmenkonto %s — Sendungen auf Rechnung, Nettopreise, Sammelrechnung zum Monatsende.',
            'liste.nummer' => 'Nummer',
            'liste.status' => 'Status',
            'liste.ziel' => 'Ziel',
            'liste.empfaenger' => 'Empfänger',
            'liste.carrier' => 'Carrier',
            'liste.referenz' => 'Referenz',
            'liste.betrag' => 'Betrag',
            'liste.netto' => 'Netto',
            'liste.datum' => 'Datum',
            'liste.angelegt_von' => 'Angelegt von',
            'liste.leer' => 'Nichts gefunden.',
            'liste.filter' => 'Filtern',
            'liste.alle_status' => 'Alle Status',
            'liste.suche' => 'Nummer, Empfänger, Referenz',
            'detail.zurueck' => '← Zurück zur Liste',
            'detail.sendung' => 'Sendung',
            'detail.absender' => 'Absender',
            'detail.empfaenger' => 'Empfänger',
            'detail.gewicht' => 'Gewichtsklasse',
            'detail.laufzeit' => 'Laufzeit',
            'detail.zahlung' => 'Zahlung',
            'detail.zahlung.revolut' => 'Revolut (Karte, Revolut Pay, Apple/Google Pay)',
            'detail.zahlung.rechnung' => 'Auf Rechnung',
            'detail.rechnung' => 'Abgerechnet mit',
            'detail.rechnung.offen' => 'noch nicht abgerechnet',
            'detail.verlauf' => 'Verlauf',
            'detail.label' => 'Versandlabel',
            'detail.label.text' => 'Das Label kommt per E-Mail, sobald es erzeugt ist. Bei Fragen: info@neos24.com mit der Nummer %s.',
            'detail.netto' => 'Netto',
            'detail.mwst' => 'MwSt.',
            'detail.brutto' => 'Brutto',
            'neu.titel' => 'Neue Sendung',
            'neu.text' => 'Nettopreis laut Firmenkonditionen, Abrechnung mit der Sammelrechnung zum Monatsende. Label folgt per E-Mail.',
            'neu.zielland' => 'Zielland',
            'neu.gewicht' => 'Gewicht',
            'neu.referenz' => 'Eigene Referenz (optional)',
            'neu.referenz.hinweis' => 'z. B. Auftragsnummer — erscheint auf der Rechnung',
            'neu.empfaenger' => 'Empfänger',
            'neu.name' => 'Name',
            'neu.strasse' => 'Straße und Hausnummer',
            'neu.plz' => 'PLZ',
            'neu.ort' => 'Ort',
            'neu.email' => 'E-Mail des Empfängers (optional, für Tracking)',
            'neu.absender' => 'Absender: %s',
            'neu.absender.fehlt' => 'Die Firmenanschrift fehlt — der Inhaber trägt sie unter „Firma“ ein.',
            'neu.preis' => 'Preis netto',
            'neu.knopf' => 'Sendung beauftragen',
            'neu.bitte_waehlen' => 'Bitte wählen',
            'neu.fehler' => 'Bitte prüfe die markierten Felder.',
            'neu.angelegt' => 'Sendung %s beauftragt. Das Label kommt per E-Mail.',
            'preise.titel' => 'Preise netto',
            'preise.text' => 'Je Paket, ohne MwSt., Abrechnung monatlich auf Rechnung. Der gezeigte Carrier ist der bevorzugte; fällt er aus, übernimmt ein Partner-Carrier zum gleichen Preis.',
            'rechnungen.titel' => 'Rechnungen',
            'rechnungen.text' => 'Sammelrechnungen deiner Firma. PDF zum Herunterladen, Positionen im Detail.',
            'rechnungen.nummer' => 'Rechnung',
            'rechnungen.zeitraum' => 'Zeitraum',
            'rechnungen.faellig' => 'Fällig',
            'rechnungen.positionen' => 'Sendungen',
            'rechnungen.pdf' => 'PDF',
            'rechnungen.keine' => 'Noch keine Rechnung — die erste kommt nach dem ersten Monat mit Sendungen.',
            'rechnungen.status.offen' => 'Offen',
            'rechnungen.status.bezahlt' => 'Bezahlt',
            'rechnungen.status.storniert' => 'Storniert',
            'benutzer.titel' => 'Benutzer',
            'benutzer.text' => 'Wer für %s Sendungen anlegen darf. Eingeladene bekommen einen Link per E-Mail.',
            'benutzer.rolle.inhaber' => 'Inhaber',
            'benutzer.rolle.mitarbeiter' => 'Mitarbeiter',
            'benutzer.einladen' => 'Einladen',
            'benutzer.eingeladen' => 'Einladung an %s verschickt.',
            'benutzer.deaktivieren' => 'Deaktivieren',
            'benutzer.aktivieren' => 'Aktivieren',
            'benutzer.erneut' => 'Erneut einladen',
            'benutzer.ausstehend' => 'Einladung offen',
            'benutzer.inaktiv' => 'inaktiv',
            'benutzer.selbst' => 'Dich selbst kannst du nicht deaktivieren.',
            'benutzer.letzter' => 'Der letzte Inhaber bleibt aktiv.',
            'firma.titel' => 'Firma',
            'firma.text' => 'Anschrift für Absender und Rechnung.',
            'firma.name' => 'Firmenname',
            'firma.strasse' => 'Straße und Hausnummer',
            'firma.plz' => 'PLZ',
            'firma.ort' => 'Ort',
            'firma.land' => 'Land',
            'firma.ust' => 'USt-IdNr. (optional)',
            'firma.rechnungs_email' => 'E-Mail für Rechnungen',
            'firma.speichern' => 'Speichern',
            'firma.gespeichert' => 'Firmendaten gespeichert.',
            'einstellungen.titel' => 'Einstellungen',
            'einstellungen.konto' => 'Konto',
            'einstellungen.name' => 'Name',
            'einstellungen.sprache' => 'Sprache',
            'einstellungen.speichern' => 'Speichern',
            'einstellungen.gespeichert' => 'Gespeichert.',
            'einstellungen.passwort' => 'Passwort',
            'einstellungen.passwort.text' => 'Ein Passwort ist optional — der Anmeldelink per E-Mail geht immer.',
            'einstellungen.passwort.gesetzt' => 'Passwort ist gesetzt.',
            'einstellungen.passwort.keins' => 'Noch kein Passwort.',
            'einstellungen.passwort.knopf' => 'Passwort ändern',
            'einstellungen.absender' => 'Absenderadresse',
            'einstellungen.absender.text' => 'Wird beim Paketversand auf der Startseite vorbelegt.',
            'einstellungen.schliessen' => 'Konto schließen',
            'einstellungen.schliessen.text' => 'Deaktiviert die Anmeldung. Bestellungen bleiben aus steuerlichen Gründen gespeichert; für eine vollständige Löschung schreib an info@neos24.com.',
            'einstellungen.schliessen.knopf' => 'Konto schließen',
            'einstellungen.schliessen.bestaetigen' => 'Konto wirklich schließen?',
            'einstellungen.geschlossen' => 'Dein Konto ist geschlossen. Danke, dass du NEOS genutzt hast.',
            'fehler.403' => 'Kein Zugriff',
            'fehler.403.text' => 'Dafür fehlt dir die Berechtigung.',
            'fehler.404' => 'Nicht gefunden',
            'fehler.404.text' => 'Diese Seite oder dieser Datensatz gehört nicht zu deinem Konto.',
            'fehler.csrf' => 'Das Formular war zu lange offen. Bitte zurück und die Seite neu laden.',
            'fehler.zur_uebersicht' => 'Zur Übersicht',
            'status.beauftragt' => 'Beauftragt',
            'ja' => 'Ja',
            'nein' => 'Nein',
        ],
        'en' => [
            'portal' => 'Customer portal',
            'anmelden' => 'Sign in',
            'abmelden' => 'Sign out',
            'zur_seite' => 'Back to website',
            'sprache_wechseln' => 'Deutsch',
            'nav.uebersicht' => 'Overview',
            'nav.bestellungen' => 'Orders',
            'nav.sendungen' => 'Shipments',
            'nav.neu' => 'New shipment',
            'nav.preise' => 'Prices',
            'nav.rechnungen' => 'Invoices',
            'nav.benutzer' => 'Users',
            'nav.firma' => 'Company',
            'nav.einstellungen' => 'Settings',
            'login.titel' => 'Sign in',
            'login.text' => 'With a password — or without: we email you a sign-in link.',
            'login.email' => 'Email',
            'login.passwort' => 'Password',
            'login.knopf' => 'Sign in',
            'login.link' => 'Email me a sign-in link',
            'login.oder' => 'or',
            'login.fehler' => 'Email or password is wrong — or the account is temporarily locked.',
            'login.kein_passwort' => 'This account has no password yet. Use the sign-in link by email and set a password afterwards.',
            'login.vergessen' => 'Forgot your password?',
            'login.registrieren' => 'No account yet? Register',
            'login.abgelaufen' => 'This link is invalid or has expired. Please request a new one.',
            'link.titel' => 'Check your inbox',
            'link.text' => 'If an account belongs to %s, an email with a link is on its way. The link is valid for %d minutes and works once.',
            'link.zurueck' => 'Back to sign in',
            'registrieren.titel' => 'Create an account',
            'registrieren.text' => 'For private customers: keep track of your orders, save your sender address. We confirm your email address by link — all orders paid with this address then appear in your account.',
            'registrieren.name' => 'Name',
            'registrieren.knopf' => 'Send confirmation link',
            'registrieren.business' => 'Business customer? Our team activates company accounts — <a href="%s">request an account</a>.',
            'vergessen.titel' => 'Forgot password',
            'vergessen.text' => 'We email you a link to set a new password.',
            'vergessen.knopf' => 'Send link',
            'passwort.titel' => 'Set a password',
            'passwort.text_neu' => 'Optional: with a password you sign in without an email link. At least %d characters.',
            'passwort.text' => 'At least %d characters.',
            'passwort.alt' => 'Current password',
            'passwort.neu' => 'New password',
            'passwort.wiederholung' => 'Repeat new password',
            'passwort.knopf' => 'Save password',
            'passwort.spaeter' => 'Later, go to overview',
            'passwort.alt_falsch' => 'The current password is wrong.',
            'passwort.ungleich' => 'The repetition does not match.',
            'passwort.gespeichert' => 'Password saved.',
            'willkommen' => 'Welcome, %s.',
            'willkommen.bestaetigt' => 'Your email address is confirmed. %d orders were linked to your account.',
            'uebersicht.privat.text' => 'All orders you paid with %s.',
            'uebersicht.letzte' => 'Recent orders',
            'uebersicht.alle' => 'Show all',
            'uebersicht.keine' => 'No orders yet. Send your first parcel from the homepage.',
            'uebersicht.paket' => 'Send a parcel',
            'uebersicht.absender' => 'Your sender address',
            'uebersicht.absender.text' => 'Prefilled for your next parcel.',
            'uebersicht.absender.fehlt' => 'None saved yet — add it under Settings.',
            'uebersicht.monat' => 'Shipments this month',
            'uebersicht.kosten' => 'Net cost this month',
            'uebersicht.offen' => 'Open invoices',
            'uebersicht.business.text' => 'Company account %s — shipments on account, net prices, one invoice at month end.',
            'liste.nummer' => 'Number',
            'liste.status' => 'Status',
            'liste.ziel' => 'Destination',
            'liste.empfaenger' => 'Recipient',
            'liste.carrier' => 'Carrier',
            'liste.referenz' => 'Reference',
            'liste.betrag' => 'Amount',
            'liste.netto' => 'Net',
            'liste.datum' => 'Date',
            'liste.angelegt_von' => 'Created by',
            'liste.leer' => 'Nothing found.',
            'liste.filter' => 'Filter',
            'liste.alle_status' => 'All statuses',
            'liste.suche' => 'Number, recipient, reference',
            'detail.zurueck' => '← Back to list',
            'detail.sendung' => 'Shipment',
            'detail.absender' => 'Sender',
            'detail.empfaenger' => 'Recipient',
            'detail.gewicht' => 'Weight class',
            'detail.laufzeit' => 'Transit time',
            'detail.zahlung' => 'Payment',
            'detail.zahlung.revolut' => 'Revolut (card, Revolut Pay, Apple/Google Pay)',
            'detail.zahlung.rechnung' => 'On account',
            'detail.rechnung' => 'Invoiced with',
            'detail.rechnung.offen' => 'not invoiced yet',
            'detail.verlauf' => 'History',
            'detail.label' => 'Shipping label',
            'detail.label.text' => 'The label arrives by email as soon as it is generated. Questions: info@neos24.com quoting %s.',
            'detail.netto' => 'Net',
            'detail.mwst' => 'VAT',
            'detail.brutto' => 'Gross',
            'neu.titel' => 'New shipment',
            'neu.text' => 'Net price at your company rates, settled with the collective invoice at month end. Label follows by email.',
            'neu.zielland' => 'Destination',
            'neu.gewicht' => 'Weight',
            'neu.referenz' => 'Your reference (optional)',
            'neu.referenz.hinweis' => 'e.g. order number — shown on the invoice',
            'neu.empfaenger' => 'Recipient',
            'neu.name' => 'Name',
            'neu.strasse' => 'Street and number',
            'neu.plz' => 'Postcode',
            'neu.ort' => 'City',
            'neu.email' => 'Recipient email (optional, for tracking)',
            'neu.absender' => 'Sender: %s',
            'neu.absender.fehlt' => 'The company address is missing — the owner adds it under “Company”.',
            'neu.preis' => 'Net price',
            'neu.knopf' => 'Book shipment',
            'neu.bitte_waehlen' => 'Please choose',
            'neu.fehler' => 'Please check the highlighted fields.',
            'neu.angelegt' => 'Shipment %s booked. The label arrives by email.',
            'preise.titel' => 'Net prices',
            'preise.text' => 'Per parcel, excluding VAT, invoiced monthly. The carrier shown is the preferred one; if unavailable, a partner carrier takes over at the same price.',
            'rechnungen.titel' => 'Invoices',
            'rechnungen.text' => 'Collective invoices of your company. PDF download, shipments in detail.',
            'rechnungen.nummer' => 'Invoice',
            'rechnungen.zeitraum' => 'Period',
            'rechnungen.faellig' => 'Due',
            'rechnungen.positionen' => 'Shipments',
            'rechnungen.pdf' => 'PDF',
            'rechnungen.keine' => 'No invoice yet — the first one follows the first month with shipments.',
            'rechnungen.status.offen' => 'Open',
            'rechnungen.status.bezahlt' => 'Paid',
            'rechnungen.status.storniert' => 'Cancelled',
            'benutzer.titel' => 'Users',
            'benutzer.text' => 'Who may create shipments for %s. Invitees receive a link by email.',
            'benutzer.rolle.inhaber' => 'Owner',
            'benutzer.rolle.mitarbeiter' => 'Staff',
            'benutzer.einladen' => 'Invite',
            'benutzer.eingeladen' => 'Invitation sent to %s.',
            'benutzer.deaktivieren' => 'Deactivate',
            'benutzer.aktivieren' => 'Activate',
            'benutzer.erneut' => 'Invite again',
            'benutzer.ausstehend' => 'invitation pending',
            'benutzer.inaktiv' => 'inactive',
            'benutzer.selbst' => 'You cannot deactivate yourself.',
            'benutzer.letzter' => 'The last owner stays active.',
            'firma.titel' => 'Company',
            'firma.text' => 'Address used as sender and on invoices.',
            'firma.name' => 'Company name',
            'firma.strasse' => 'Street and number',
            'firma.plz' => 'Postcode',
            'firma.ort' => 'City',
            'firma.land' => 'Country',
            'firma.ust' => 'VAT ID (optional)',
            'firma.rechnungs_email' => 'Email for invoices',
            'firma.speichern' => 'Save',
            'firma.gespeichert' => 'Company details saved.',
            'einstellungen.titel' => 'Settings',
            'einstellungen.konto' => 'Account',
            'einstellungen.name' => 'Name',
            'einstellungen.sprache' => 'Language',
            'einstellungen.speichern' => 'Save',
            'einstellungen.gespeichert' => 'Saved.',
            'einstellungen.passwort' => 'Password',
            'einstellungen.passwort.text' => 'A password is optional — the sign-in link by email always works.',
            'einstellungen.passwort.gesetzt' => 'Password is set.',
            'einstellungen.passwort.keins' => 'No password yet.',
            'einstellungen.passwort.knopf' => 'Change password',
            'einstellungen.absender' => 'Sender address',
            'einstellungen.absender.text' => 'Prefilled when you send a parcel from the homepage.',
            'einstellungen.schliessen' => 'Close account',
            'einstellungen.schliessen.text' => 'Disables sign-in. Orders stay stored for tax reasons; for full deletion write to info@neos24.com.',
            'einstellungen.schliessen.knopf' => 'Close account',
            'einstellungen.schliessen.bestaetigen' => 'Really close your account?',
            'einstellungen.geschlossen' => 'Your account is closed. Thank you for using NEOS.',
            'fehler.403' => 'No access',
            'fehler.403.text' => 'You do not have permission for this.',
            'fehler.404' => 'Not found',
            'fehler.404.text' => 'This page or record does not belong to your account.',
            'fehler.csrf' => 'The form was open for too long. Please go back and reload the page.',
            'fehler.zur_uebersicht' => 'To overview',
            'status.beauftragt' => 'Booked',
            'ja' => 'Yes',
            'nein' => 'No',
        ],
    ];

    return $t;
}
