// Beispieldaten für die Vorschau im Vorlagen-Editor – erfundene Namen und Inhalte.
import { fromBerlin } from "@/lib/dates";

export function sampleContext(appUrl: string) {
  const beginn = fromBerlin(2026, 11, 12, 19, 0);
  return {
    ov: {
      name: "Seckenheim-Friedrichsfeld",
      nameLang: "CDU Mannheim-Süd / Seckenheim-Friedrichsfeld",
      nameAnschrift: "CDU OV Mannheim-Süd Seckenheim-Friedrichsfeld",
      ort: "Mannheim",
      absenderzeile: "",
      appUrl,
    },
    absender: { name: "Max Muster", funktion: "Ortsvorsitzender" },
    empfaenger: { name: "Erika Beispiel", anrede: "Sehr geehrte Frau Beispiel" },
    sitzung: {
      art: "Vorstandssitzung",
      artGenitiv: "Vorstandssitzung",
      beginn,
      ort: "Gasthaus Beispiel, Musterstraße 1, 68239 Mannheim",
      onlineLink: "",
      eroeffnetUm: fromBerlin(2026, 11, 12, 19, 5),
      geschlossenUm: fromBerlin(2026, 11, 12, 20, 40),
      unterbrechung: "",
      sitzungsleitung: "Max Muster, Ortsvorsitzender",
      einladungVom: fromBerlin(2026, 11, 5, 10, 0),
      einladungsweg: "per E-Mail",
      zusageLink: `${appUrl}/rsvp/beispiel`,
      absagegrund: "",
      rueckmeldungBis: fromBerlin(2026, 11, 10),
      beschlussfaehig: true,
      quorumAnwesend: 7,
      quorumStimmberechtigt: 10,
      feststellungDurch: "den Ortsvorsitzenden",
      wiederholungNachBeschlussunfaehigkeit: false,
      eilbeduerftig: false,
      eilbeduerftigBegruendung: "",
    },
    vorherigeSitzung: { beginn: fromBerlin(2026, 11, 5, 19, 0) },
    letztesProtokoll: { sitzungsdatum: fromBerlin(2026, 10, 15, 19, 0) },
    tagesordnung: [
      { nummer: "1", titel: "Begrüßung durch den Vorsitzenden", ebene: 0, status: "BEHANDELT" },
      { nummer: "1.1", titel: "Bericht aus dem CDU Kreisverband Mannheim", ebene: 1, status: "BEHANDELT" },
      { nummer: "2", titel: "Genehmigung des Protokolls der Sitzung vom 15.10.2026", ebene: 0, status: "BEHANDELT" },
      { nummer: "3", titel: "Planung Infostand Weihnachtsmarkt", ebene: 0, status: "BEHANDELT" },
      { nummer: "4", titel: "Termine", ebene: 0, status: "BEHANDELT" },
      { nummer: "5", titel: "Sonstiges", ebene: 0, status: "BEHANDELT" },
    ],
    protokoll: {
      protokollfuehrung: "Max Muster",
      version: 1,
      aenderungshinweis: "",
      link: `${appUrl}/meetings/beispiel/minutes`,
      formalia: {
        eroeffnung: "Der Ortsvorsitzende eröffnet die Sitzung um 19:05 Uhr und begrüßt die Anwesenden.",
        wiedereroeffnung: "",
        tagesordnung: "Die Tagesordnung wird ohne Änderungen angenommen.",
        letztesProtokoll: "Das Protokoll der Sitzung vom 15.10.2026 wird einstimmig genehmigt.",
      },
      abschnitte: [
        {
          topNummer: "3",
          topTitel: "Planung Infostand Weihnachtsmarkt",
          punkte: [{ text: "Planung: Infostand am 12.12. von 10 bis 14 Uhr.", unterpunkte: ["Material: Flyer, Kugelschreiber"] }],
          ergebnis: { art: "BESCHLUSS", text: "Der Infostand wird einstimmig beschlossen." },
          notiz: "Standplatz mit dem Marktamt abgestimmt.",
          anlagen: [{ nummer: 1, name: "Lageplan-Weihnachtsmarkt.pdf" }],
        },
      ],
      unterzeichner: [
        { name: "Max Muster", funktion: "Ortsvorsitzender / Protokoll" },
        { name: "Erika Beispiel", funktion: "stellv. Vorsitzende" },
      ],
    },
    anwesenheit: [
      { name: "Max Muster", funktion: "Ortsvorsitzender", status: "ANWESEND" },
      { name: "Erika Beispiel", funktion: "stellv. Vorsitzende", status: "ENTSCHULDIGT" },
    ],
    umlaufbeschluesse: [],
    beschluesse: [{ top: "3", gegenstand: "Infostand Weihnachtsmarkt", ergebnisText: "einstimmig angenommen" }],
    aufgaben: [{ nr: 1, titel: "Material bestellen", verantwortlich: "Muster", frist: "01.12.2026" }],
    umlauf: {
      betreff: "Genehmigung des Protokolls vom 12.11.2026",
      text: "Der Vorstand genehmigt das Protokoll der Vorstandssitzung vom 12.11.2026.",
      begruendung: "",
      frist: fromBerlin(2026, 11, 26),
      link: `${appUrl}/vote/beispiel`,
      nummer: "U-2026-01",
      stimmberechtigt: 10,
      erforderlich: 6,
      ja: 7,
      nein: 0,
      enthaltung: 1,
      widerspruch: 0,
      ohneRueckmeldung: 2,
      angenommen: true,
      ergebnisText: "Der Beschluss ist mit 7 von 10 Stimmen der Stimmberechtigten angenommen (erforderlich: 6).",
      protokoll: true,
    },
    aufgabe: {
      titel: "Material bestellen",
      frist: fromBerlin(2026, 12, 1),
      ueberfaellig: false,
      herkunft: "Sitzung vom 12.11.2026 · TOP „Planung Infostand Weihnachtsmarkt“",
      link: `${appUrl}/tasks/beispiel`,
      von: "Max Muster",
    },
    aktion: {
      titel: "Infostand Weihnachtsmarkt",
      beginn: fromBerlin(2026, 12, 12, 10, 0),
      ort: "Rathausplatz Seckenheim",
      beschreibung: "Wir verteilen Glühwein und Flyer.",
      link: `${appUrl}/actions/beispiel`,
    },
    schichten: [
      { beginn: fromBerlin(2026, 12, 12, 10, 0), ende: fromBerlin(2026, 12, 12, 12, 0), offen: 1, benoetigt: 3 },
      { beginn: fromBerlin(2026, 12, 12, 12, 0), ende: fromBerlin(2026, 12, 12, 14, 0), offen: 2, benoetigt: 3 },
    ],
    anmeldung: { link: `${appUrl}/api/auth/callback/email?token=beispiel`, gueltigMinuten: 15 },
    zugang: { link: `${appUrl}/login` },
    emailAenderung: {
      neueAdresse: "neu@example.org",
      alteAdresse: "alt@example.org",
      link: `${appUrl}/email-confirm/beispiel`,
      gueltigStunden: 24,
    },
    antrag: { titel: "Sondersitzung Haushalt", beschreibung: "", unterstuetzer: 5, erforderlich: 5, link: `${appUrl}/meetings/proposals` },
    transkript: { sitzung: "Vorstandssitzung am 12.11.2026", link: `${appUrl}/meetings/beispiel/minutes` },
    inventar: {
      stand: "08.10.2026",
      filter: "",
      anzahl: 1,
      inventur: false,
      positionen: [
        { code: "OVMASF00001.24", name: "Pavillon 3 × 3 m", kategorie: "Infostand", standort: "Lager", menge: 1, zustand: "gut", verliehenAn: "", faellig: "", ausgemustert: false },
      ],
    },
    auslage: {
      nummer: "A-2026-01",
      titel: "Material Infostand Weihnachtsmarkt",
      anlass: "Infostand am 12.12.2026",
      antragsteller: "Max Muster",
      erstellt: fromBerlin(2026, 12, 14, 10, 0),
      erstattungsart: "Überweisung",
      spende: false,
      ueberweisung: true,
      bar: false,
      kontoinhaber: "Max Muster",
      iban: "DE89 3704 0044 0532 0130 00",
      anschrift: "",
      bemerkung: "",
      summe: "42,50 €",
      positionen: [{ nr: 1, belegdatum: "10.12.2026", beschreibung: "Glühwein und Becher", betrag: "42,50 €", beleg: "Beleg 1" }],
      freigabeDurch: "",
      freigabeAm: "",
    },
    beschluss: {
      nummer: "2026-07",
      gremium: "Vorstand der CDU Mannheim-Süd / Seckenheim-Friedrichsfeld",
      gegenstand: "Antrag zur Verkehrsberuhigung der Hauptstraße",
      datum: fromBerlin(2026, 10, 13, 19, 0),
      verfahren: "Vorstandssitzung (Restaurant Beispiel)",
      top: "4",
      topTitel: "Verkehr",
      ergebnisText: "einstimmig angenommen",
      stimmen: "Ja 7, Nein 0, Enthaltung 1",
      beschlussfaehigkeit: "gegeben (8 von 11 Stimmberechtigten anwesend)",
      wortlaut: "Der Vorstand beschließt, beim Kreisverband zu beantragen …",
      begruendung: "",
      ausgestelltAm: fromBerlin(2026, 10, 14, 10, 0),
    },
    eingabe: {
      titel: "Verkehrsberuhigung der Hauptstraße",
      empfaenger: "CDU-Kreisverband Mannheim\nKreisvorstand",
      datum: fromBerlin(2026, 10, 14, 10, 0),
      text: "Der Kreisvorstand möge beschließen: …",
      begruendung: "Beispielbegründung",
    },
    seite: { titel: "Sommerfest 2027", link: `${appUrl}/p/sommerfest` },
    bestaetigung: { link: `${appUrl}/bestaetigen/beispiel`, loeschfristTage: 90, datenschutz: "https://www.cdu-sf.de/datenschutz/" },
    pm: {
      titel: "CDU fordert sichere Schulwege in Seckenheim",
      untertitel: "Ortsverband legt Vorschläge für die Hauptstraße vor",
      datum: "06.10.2026",
      text: "Mannheim-Seckenheim. Der Ortsverband … (Beispieltext)",
      link: `${appUrl}/presse/sichere-schulwege`,
    },
    pressekontakt: "Erika Beispiel, Pressesprecherin\npresse@example.org",
    abmeldeLink: `${appUrl}/presse/abmelden/beispiel`,
  };
}
